[package]
name = "hello-world"
version = "0.0.0"
edition = "2024"

[dependencies]
wasm-bindgen-futures = "0.4"
gloo = { version = "0.11", features = ["default"] }
socketio-client-wasm = { workspace = true }
