[package]
name = "js-raw"
version = "0.0.0"
edition = "2024"
build = "build.rs"

[dependencies]
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
gloo = { version = "0.11", features = ["default"] }   # todo

[build-dependencies]
reqwest = { version = "0.13", features = ["blocking"] }
